name: 'devcontainer-build-run'
description: 'Action to simplify using VS Code dev containers in GitHub workflows'
author: 'stuartleeks'
branding:
  color: purple
  icon: box
inputs:
  imageName:
    required: true
    description: Image name (including registry)
  imageTag:
    required: false
    description: Image tag (defaults to latest)
  runCmd:
    required: true
    description: Specify the command to run after building the dev container image
  subFolder:
    required: false
    description: Specify a child folder (containing a .devcontainer) instead of using the repository root
    default: 
  checkoutPath:
    required: false
    description: Specify path to checked out folder if not using default (or for testing with nektos/act)
    default: .
  push:
    required: false
    default: filter
    description: Control when images are pushed. Options are never, filter, always. For filter (default), images are pushed if the refFilterForPush and eventFilterForPush conditions are met
  refFilterForPush:
    required: false
    default:
    description: Set the source branches (e.g. refs/heads/main) that are allowed to trigger a push of the dev container image. Leave empty to allow all.
  eventFilterForPush:
    required: false
    default: push
    description: Set the event names (e.g. pull_request, push) that are allowed to trigger a push of the dev container image. Defaults to push. Leave empty for all
  env:
    required: false
    description: Specify environment variables to pass to the docker run command
  skipContainerUserIdUpdate:
    required: false
    default: false
    description: For non-root dev containers (i.e. where `remoteUser` is specified), the action attempts to make the container user UID and GID match those of the host user. Set this to true to skip this step (defaults to false)
  privileged:
    required: false
    default: false
    description: Control whether extended privileges are given to the devcontainer (i.e. using --privileged option). This is needed for dev containers configured with docker-in-docker. Set this to true to grant extended privileges (defaults to false)
runs:
  using: 'node12'
  main: 'github-action/dist/index.js'
  post: 'github-action/dist/index.js'
  post-if: 'success()'
